### ISSUE TITLE
Obsolete and broken. Can not be used.

### ISSUE THREAD

**Issue by alexb3d** [flathub/com.vinszent.GnomeTwitch#10]
The first warning it gives when updating is:
`org.gnome.Platform is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.`

Before it could be used, now it cannot load the channels.
`Unable to fetch all followed channels because: Unable to read JSON member with name '_total' because: El miembro «_total» no está definido en el objeto en la posición actual.`

**Comment by garrett** [comment]
The [project's last update was early 2019](https://github.com/vinszent/gnome-twitch/) and the Twitch API has changed since then, so the client itself is broken, not just the Flatpak version of it.

It should be EOL'd and delisted from Flathub. :frowning_face:
