### ISSUE TITLE
outdated package

### ISSUE THREAD

**Issue by speace** [flathub/com.vinszent.GnomeTwitch#2]
Due to a recent change in twitch API (force using SSL) this version of gnome-twitch wont work anymore so the package is outdated.  
Unfortunatly I have no idea how flatpak works to make a PR to update gnome-twitch.

**Comment by Lonsfor** [comment]
I thing that should do it

**Comment by nedrichards** [comment]
The fixes in https://github.com/flathub/com.vinszent.GnomeTwitch/commit/bb73e96436ba2ee4c78addb0a087e91701a58ada should have fixed this, and I have a PR in #4 for an overall update that also includes that fix.
