### ISSUE TITLE
Provide all backends?

### ISSUE THREAD

**Issue by jaystrictor** [flathub/com.vinszent.GnomeTwitch#7]
(There is an [issue in the gnome-twitch repo](https://github.com/vinszent/gnome-twitch/issues/364) about this already, but I think it belongs here?)

Unfortunately, only Cairo and OpenGL backends are available for the flatpak version of gnome-twitch. Is there a chance to include MPV and Clutter backends in the flatpak package?

**Comment by TingPing** [comment]
Clutter is not a library anybody should be using anymore and MPV increases the amount of things to build and maintain by 10x.

I don't plan on changing that. If somebody wants to make an extension point for the MPV backend I'd consider it.

**Comment by jaystrictor** [comment]
> Clutter is not a library anybody should be using anymore

Oh, ..., ok. Everytime I open a bug report, I learn something new form you :D
Why is it that Clutter should not be used anymore? I cannot find any mention of deprecation or something like that.

> and MPV increases the amount of things to build and maintain by 10x.
> I don't plan on changing that. If somebody wants to make an extension point for the MPV backend I'd consider it.

Fair enough. I try to fix the severe stuttering that I experience with Cairo by some other means.

**Comment by TingPing** [comment]
> Why is it that Clutter should not be used anymore? I cannot find any mention of deprecation or something like that.

Much of Clutters main features have been moved into GTK4 and the biggest remaining consumer of Clutter is GNOME-Shell (they actually just copy paste the entire project into it as a private library: https://github.com/GNOME/mutter/tree/master/clutter).

So while it is still maintained its future is entirely tied to the needs of the shell. Other applications using it are either unmtaintained or have been planning on moving away from Clutter for many years.

Also in those years GStreamer has gained an OpenGL sink and GTK3 gained an OpenGL widget so it doesn't make sense to add Clutter just for that.
